version: '3'
services:
   my_hotpepper_web_app_1:
     build: .
     volumes:
      - ./my_hotpepper_web_app:/usr/src/app
      - /usr/src/app/node_modules      ## バインドマウント
     command: sh -c "yarn start"
     ports:
      - "3000:3000"     

# 参考：https://blog.web.nifty.com/engineer/2714
# React で，create-react-app　していない場合
# In> docker-compose build
# In> docker-compose run --rm my_hotpepper_web_app sh -c "npm install -g create-react-app && create-react-app my_hotpepper_web_app"